/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./resources/js/components/ActionMessage.vue')['default']
    ActionSection: typeof import('./resources/js/components/ActionSection.vue')['default']
    ApplicationLogo: typeof import('./resources/js/components/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./resources/js/components/ApplicationMark.vue')['default']
    AuthenticationCard: typeof import('./resources/js/components/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./resources/js/components/AuthenticationCardLogo.vue')['default']
    Banner: typeof import('./resources/js/components/Banner.vue')['default']
    Checkbox: typeof import('./resources/js/components/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./resources/js/components/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./resources/js/components/ConfirmsPassword.vue')['default']
    DangerButton: typeof import('./resources/js/components/DangerButton.vue')['default']
    DialogModal: typeof import('./resources/js/components/DialogModal.vue')['default']
    Dropdown: typeof import('./resources/js/components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/components/DropdownLink.vue')['default']
    FormSection: typeof import('./resources/js/components/FormSection.vue')['default']
    InputError: typeof import('./resources/js/components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/components/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/components/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./resources/js/components/SectionBorder.vue')['default']
    SectionTitle: typeof import('./resources/js/components/SectionTitle.vue')['default']
    TextInput: typeof import('./resources/js/components/TextInput.vue')['default']
    Welcome: typeof import('./resources/js/components/Welcome.vue')['default']
  }
}
